name: CI Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Check app
        run: node -e "require('./index.js')"

      - name: Build Docker image
        run: docker build -t devops-app .